# permissions for end users to edit clientapps.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: clientapp-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: clientapp-operator
    app.kubernetes.io/part-of: clientapp-operator
    app.kubernetes.io/managed-by: kustomize
  name: clientapp-editor-role
rules:
- apiGroups:
  - app.mfabriczy
  resources:
  - clientapps
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - app.mfabriczy
  resources:
  - clientapps/status
  verbs:
  - get
