---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - app.mfabriczy
  resources:
  - clientapps
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - app.mfabriczy
  resources:
  - clientapps/finalizers
  verbs:
  - update
- apiGroups:
  - app.mfabriczy
  resources:
  - clientapps/status
  verbs:
  - get
  - patch
  - update
