apiVersion: app.mfabriczy/v1
kind: ClientApp
metadata:
  labels:
    app.kubernetes.io/name: clientapp
    app.kubernetes.io/instance: clientapp-sample
    app.kubernetes.io/part-of: clientapp-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: clientapp-operator
  name: clientapp-sample
spec:
# TODO(user): Add fields here.
  name: clientapp-instance 
  image: nginx:1.25
  replicas: 3
  env:
    - name: environment
      value: "production"
  port: 8080
  portname: http
  host: example.com
  resources:
    requests:
      memory: "64Mi"
      cpu: "250m"
    limits:
      memory: "128Mi"
      cpu: "500m"
